apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: auea
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: auea
    app.kubernetes.io/part-of: byoc-app-tojv
  name: auea
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: auea
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: auea
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-xxzf-tenant/byoc-app-tojv/auea@sha256:07b90d1a5bb164ab34f56d6630164ea08c130d9fefe29478b75984032a3e9912
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
