apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: auea
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: auea
    app.kubernetes.io/part-of: byoc-app-tojv
  name: auea3psf
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: auea
    weight: null
status: {}
